-- Whisper Anywhere hosted-mode schema
-- Run in Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key,
  email text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  status text not null default 'active'
);

create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  daily_transcription_count integer not null default 0,
  daily_audio_ms bigint not null default 0,
  daily_estimated_usd numeric(12,6) not null default 0,
  day_bucket date not null default (now() at time zone 'utc')::date,
  unique (user_id, device_id)
);

create table if not exists public.usage_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  device_id text not null,
  request_id text not null,
  audio_ms bigint not null default 0,
  estimated_usd numeric(12,6) not null default 0,
  created_at timestamptz not null default now(),
  status text not null,
  unique (request_id)
);

create table if not exists public.budget_state (
  day_bucket date primary key,
  estimated_usd_total numeric(12,6) not null default 0,
  hard_stop_triggered boolean not null default false,
  updated_at timestamptz not null default now()
);

create index if not exists idx_devices_user_device on public.devices(user_id, device_id);
create index if not exists idx_usage_ledger_created_at on public.usage_ledger(created_at desc);

alter table public.profiles enable row level security;
alter table public.devices enable row level security;
alter table public.usage_ledger enable row level security;
alter table public.budget_state enable row level security;

-- Backend uses service role key; deny anon direct table access.
revoke all on public.profiles from anon, authenticated;
revoke all on public.devices from anon, authenticated;
revoke all on public.usage_ledger from anon, authenticated;
revoke all on public.budget_state from anon, authenticated;
